# Generated by Django 2.0 on 2018-12-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20181206_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='posts',
            field=models.IntegerField(default=0),
        ),
    ]
