# Generated by Django 2.0 on 2018-12-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
