# Generated by Django 2.0 on 2018-12-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_category_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
