# Generated by Django 2.0 on 2018-12-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20181209_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
