# Generated by Django 2.0.10 on 2019-02-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_remove_topic_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='locked',
        ),
    ]
