# Generated by Django 2.0 on 2018-11-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181120_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='forum_tag',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
