# Generated by Django 2.0 on 2018-12-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='forum',
        ),
    ]
