# Generated by Django 2.0.10 on 2019-02-10 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_remove_topic_views'),
        ('blog', '0008_auto_20181218_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='forum_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Topic'),
        ),
    ]
