# Generated by Django 2.0 on 2018-11-22 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('topic', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NS', 'Not Started'), ('ST', 'Started'), ('DN', 'Done')], default='NS', max_length=2)),
                ('upvotes', models.IntegerField(default=0)),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
