# Generated by Django 2.0 on 2018-11-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
