# Generated by Django 2.0 on 2018-11-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20181122_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Started', 'Started'), ('Done', 'Done')], default='Not Started', max_length=12),
        ),
    ]
