# Generated by Django 2.0 on 2018-12-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20181206_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='forum',
        ),
    ]
