# Generated by Django 2.0.10 on 2019-01-29 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20181218_1834'),
        ('tickets', '0007_auto_20181218_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='forum_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Topic'),
        ),
    ]
